## NEW Synthetic control {#sec-synth}

The synthetic control method [@abadieSyntheticControlMethods2010; @cunninghamCausalInferenceMixtape2021, ch. 10] leverages the idea of comparing a region where a protest happens with other regions where no protest happens on the same day. However it goes beyond a simple comparison. Instead it constructs a _synthetic region_ from all the control regions that is as close as possible to the treatment region. The synthetic region can then be used to model the counterfactual of no protest for the treatment region.

### Theory

I assume that the outcome of each region $r \in R$ is given by a _factor model_ [inspired by @abadieSyntheticControlMethods2010]:

$$
E(Y_r|X_r,W_r,U) = \beta + \beta_X X_r + \beta_W W_r + \beta_U U + \sum_{i=0}^{|X_r|} \sum_{j=0}^{|U|} \beta_{UX,ij} (X_r U^T)_{ij}
$$

where $Y_r$ is the outcome for region $r$, $X_r$ is a vector of known covariates of region $r$, $U$ is a vector of unknown global confounders, and $X_r U^T$ is a $|X_r|\times |U|$ matrix of interactions between the regional covariates and the unknown global confounders; $\beta, \beta_X, \beta_W, \beta_U, \beta_{UX}$ are global parameters of the model (with sizes that correspond to the respective variables) that specify the impact of the variables on the outcome variable; and $\epsilon_r$ an error term with mean $0$.

The model allows for time-variant hidden confounders $U$ that are the same across all regions. And through the term $X_r U^T$ it also allows for interactions of the confounders with the regional covariates, including static ones as well as time-variant ones.

The counterfactual is given by omitting the impact of the treatment:

$$
E(Y_r(0)|X_r,W_r,U) = \beta + \beta_X X_r + \beta_U U + \sum_{i=0}^{|X_r|} \sum_{j=0}^{|U|} \beta_{UX,ij} (X_r U^T)_{ij}
$$

Let $R_0 = \{r \in R|W_r=0\}$ be the set of control regions. Assume the existence of scalar weights $\gamma_s$ for all $s \in R_0$ that allow the interpolation of the covariates of the treatment region from the covariates of the control region:

\begin{align}
\sum_{s \in R_0} \gamma_s = 1 \text{ and } \gamma_s \geq 0\: \forall s \in R_0 && \text{Convexity} \label{eq-convex} \\
E\left(\sum_{s \in R_0} \gamma_s X_s\right) = E(X_r) && \text{Interpolation} \label{eq-interpol}
\end{align}

Then by interpolating the counterfactual from the control regions we obtain the estimator $\hat Y_r(0) = \sum_{s \in R_0} \gamma_s Y_s$:

::: {.column-page}
\begin{align}
E(\hat Y_r(0)) &= E\left\{ \sum_{s \in R_0} \gamma_s Y_s \right\} \\
&= E\left\{ \sum_{s \in R_0} \gamma_s E(Y_s|X_s,W_s,U) \right\} \\
&= E\left\{ \sum_{s \in R_0} \gamma_s E\left[\beta + \beta_X X_s + \beta_U U + \sum_{i=0}^{|X_r|} \sum_{j=0}^{|U|} \beta_{UX,ij} (X_s U^T)_{ij} \right] \right\} \\
&= E\left\{ \beta + \beta_X E\left(\sum_{s \in R_0} \gamma_s  X_s\right) + \beta_U U + \sum_{i=0}^{|X_r|} \sum_{j=0}^{|U|} \beta_{UX,ij} \left[E\left(\sum_{s \in R_0} \gamma_s  X_s\right) U^T\right]_{ij} \right\} && \text{by assumption \eqref{eq-convex}} \\
&= E\left\{ \beta + \beta_X X_r + \beta_U U + \sum_{i=0}^{|X_r|} \sum_{j=0}^{|U|} \beta_{UX,ij} (X_r U^T)_{ij} \right\} && \text{by assumption \eqref{eq-interpol}} \\
&= E\left\{ Y_r(0) \right\}
\end{align}
:::

The ATT can thus be estimated by:

\begin{align}
\tau_r &= E(Y_r|W=1) - E(Y_r(0)|W=1) \\
&= E(Y|W=1) - E(\sum_{s \in R_0} \gamma_s Y_s|W=1) \\
&= E(Y|W=1) - \sum_{s \in R_0} \gamma_s E(Y_s|W=1)
\end{align}

In this setting it is not straightforward to single out the effect of different protest groups because there is no way to directly control for co-occurring protest events; therefore I only compute the average effect for all groups.

Weights $\gamma$ can be obtained by "upside down regression" [@facurealvesCausalInferenceBrave2022, ch. 15] to estimate $E(X_r)=\gamma_1 X_1 + ... + \gamma_n X_n$ for the control regions $1...n=R_0$. In principle, we can use OLS or nonnegative least squares (NLS) for the estimation. However, this allows the model to _extrapolate_ rather than _interpolate_ between the control regions. To estimate weights that interpolate (that is, they are positive and sum up to 1), we can define a loss function $\left|X_r - \sum_{s \in R_0} \gamma_s X_s\right|$ and minimize it subject to the positivity and sum constraints on the weights, for example by using quadratic programming as minimization technique [@facurealvesCausalInferenceBrave2022, ch. 15; @abadieSyntheticControlMethods2010].

Since the available control regions vary from day to day, many regressions have to be run. $X_r$ may be chosen to either represent (static) fundamental data about the regions that is suspected to be predictive of treatment or outcome [@abadieSyntheticControlMethods2010]; or it can just be previous time-series information about the outcome and other variables [@facurealvesCausalInferenceBrave2022, ch. 15].

@fermanSyntheticControlsImperfect2021 suggest that demeaning the data based on the pre-treatment period makes the synthetic control method more robust.

<!--

cite Abadie, Cunningham

### Selecting control regions based on the distance

- reverse and effect

### Selecting control regions based on sociodemographics

Variables

Methods:
- correlation
- linear regression
- PC regression
- PLS regression
- NMF regression

visualize "maps of Germany" based on first 2 components

select n_components based on cross-validation

### Selecting control regions based on high predictive quality

#### manually

#### using tf-causalimpact

### Bias from incomplete protest data

#### Difficulties with small protest events

#### Difficulties with large protest events -->

<!-- ### Evaluation

- Placebo
- balance of the covariates (=how good are the synthetic units in fundamental terms?)
- pre-treatment fit?
- (p-values) -->
