project:
  title: "Thesis"
  output-dir: _output
  execute-dir: project
bibliography: [references.bib]
csl: chicago-author-date.csl
reference-location: margin
citation-location: margin
format:
  pdf:
    number-sections: true
    colorlinks: true
    mainfont: "Lato Light"
    sansfont: "Lato Black"
    link-citations: true
    papersize: a4
    lang: en
    fontsize: 9pt
    include-in-header:
      text: |
        \usepackage[l3]{csvsimple}
        \usepackage{booktabs}
        \usepackage{url}
        \def\UrlBreaks{\do\/\do-\do.\do=\do_\do?\do\&\do\%\do\a\do\b\do\c\do\d\do\e\do\f\do\g\do\h\do\i\do\j\do\k\do\l\do\m\do\n\do\o\do\p\do\q\do\r\do\s\do\t\do\u\do\v\do\w\do\x\do\y\do\z\do\A\do\B\do\C\do\D\do\E\do\F\do\G\do\H\do\I\do\J\do\K\do\L\do\M\do\N\do\O\do\P\do\Q\do\R\do\S\do\T\do\U\do\V\do\W\do\X\do\Y\do\Z\do\0\do\1\do\2\do\3\do\4\do\5\do\6\do\7\do\8\do\9}
  html:
    toc: true
    toc-depth: 5
    mainfont: "Lato Light"
    sansfont: "Lato Black"
    lang: en
  md:
    toc: true
    toc-depth: 5
